server:
  port: 80

spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mychatgpt?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ttpfx.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


gpt:
  model:
    key: 必填
proxy:
  host: 127.0.0.1
  port: 7890